/**
 * plugins/matagi/agents/*.md（Markdown + frontmatter）を、
 * Codex CLI のカスタムエージェント定義 <出力先>/agents/<name>.toml へ変換するスクリプト。
 *
 * マッピング: frontmatter の name → name / description → description、
 * frontmatter 以降の本文 → developer_instructions（Codex の必須3フィールド）。
 * frontmatter を持たないファイル（README.md 等）のみ変換対象外として静かに読み飛ばす。
 * frontmatter があるのに name / description 欠落・name 不正・name 重複はエラーで中止する。
 *
 * 安全性:
 * - 出力先（および <出力先>/agents の symlink 解決後）がソースツリー配下・同一なら中止する。
 * - 既存の agents/<name>.toml が今回の生成物と内容が異なる場合は --force 無しでは何も書かずに失敗する
 *   （同内容は冪等に許可）。--force で上書きする。通常ファイルでも symlink でもない既存（ディレクトリ等）は
 *   --force でも拒否する。書き込みは同一ディレクトリの一時ファイル経由の renameSync 置換で、
 *   symlink / ハードリンクのリンク先 inode は書き換えない。
 * - 生成物の先頭に GENERATED_MARKER を付け、ソースから削除・改名されたエージェントの古い .toml のうち
 *   マーカーを持つもの（本生成器の出力）だけを削除する。マーカーの無い（ユーザー自作の）.toml は削除しない。
 *   ソースの .md が 0 件のときは（ディレクトリ誤指定による全削除を防ぐため）削除自体をスキップする。
 *
 * 実行方法: node --experimental-strip-types generate-agents-toml.ts <出力先ディレクトリ（例: <repo>/.codex）> [--force]
 */

import {
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
} from "node:fs";
import { join, resolve } from "node:path";
import {
  assertOutsideSource,
  assertReplaceableOutput,
  isDirectRun,
  parseOutputDirArgs,
  realpathNonStrict,
  writeFileReplacing,
} from "../shared.ts";
import { tomlMultilineString, tomlString } from "./toml.ts";

const SOURCE_PLUGIN_ROOT = join(import.meta.dirname, "../../");
const SOURCE_AGENTS_DIR = join(SOURCE_PLUGIN_ROOT, "agents");

// 先頭の `---` で囲まれた frontmatter と、それ以降の本文
const FRONTMATTER_PATTERN = /^---\n([\s\S]*?)\n---(?:\n|$)([\s\S]*)$/;

/** 本生成器の出力であることを示す先頭行のマーカー（古い出力の識別・削除に使う）。 */
export const GENERATED_MARKER =
  "# generated by matagi adapters/codex/generate-agents-toml.ts (do not edit; regenerate instead)";

export type AgentDefinition = {
  name: string;
  description: string;
  instructions: string;
};

// 出力ファイル名 <name>.toml になるため、パス区切り等を含められない安全な文字種に限定する
const AGENT_NAME_PATTERN = /^[a-z0-9-]+$/;

/**
 * 単一行 `key: value` 形式の frontmatter から指定キーの値を取り出す。キーが無ければ null。
 * 値が空、ブロックスカラー（`|` `>` 始まり）、引用符付き、次行が字下げで続く複数行プレーン値の場合は
 * 未対応形式として Error を投げる。
 */
export const frontmatterValue = (
  frontmatter: string,
  key: string,
): string | null => {
  const lines = frontmatter.split("\n");
  const keyPattern = new RegExp(`^${key}:[ \\t]*(.*)$`);
  const index = lines.findIndex((line) => keyPattern.test(line));
  if (index === -1) {
    return null;
  }
  const value = (lines[index].match(keyPattern) as RegExpMatchArray)[1].trim();
  const nextLine = lines[index + 1];
  const continues = nextLine !== undefined && /^[ \t]+\S/.test(nextLine);
  if (value === "" || /^[|>"']/.test(value) || continues) {
    throw new Error(
      `未対応の frontmatter 形式です（${key}: は単一行の引用符なしプレーン値のみ対応。複数行値・ブロックスカラー・引用符は不可）`,
    );
  }
  return value;
};

/**
 * Markdown 1ファイルを AgentDefinition に変換する。
 * frontmatter が無ければ null（README.md 等。静かに変換対象外）。
 * frontmatter があるのに name / description が欠落、または name が不正なら Error を投げる。
 * @param label エラーメッセージ用のファイル名
 */
export const parseAgent = (
  source: string,
  label: string = "(unknown)",
): AgentDefinition | null => {
  const match = source.replaceAll("\r\n", "\n").match(FRONTMATTER_PATTERN);
  if (!match) {
    return null;
  }
  let name: string | null;
  let description: string | null;
  try {
    name = frontmatterValue(match[1], "name");
    description = frontmatterValue(match[1], "description");
  } catch (error) {
    throw new Error(
      `${label}: ${error instanceof Error ? error.message : String(error)}`,
    );
  }
  if (!name || !description) {
    throw new Error(
      `${label}: frontmatter に name / description の両方が必要です`,
    );
  }
  if (!AGENT_NAME_PATTERN.test(name)) {
    throw new Error(
      `${label}: name は ${AGENT_NAME_PATTERN} に一致する必要があります: ${name}`,
    );
  }
  return { name, description, instructions: match[2].trim() + "\n" };
};

/** 複数ファイルを変換し、frontmatter 無しは除外する。name が重複したら Error を投げる。 */
export const parseAgents = (
  sources: { file: string; content: string }[],
): AgentDefinition[] => {
  const agents: AgentDefinition[] = [];
  const fileByName = new Map<string, string>();
  for (const { file, content } of sources) {
    const agent = parseAgent(content, file);
    if (agent === null) {
      continue;
    }
    const existing = fileByName.get(agent.name);
    if (existing !== undefined) {
      throw new Error(
        `agent name "${agent.name}" が重複しています: ${existing} / ${file}`,
      );
    }
    fileByName.set(agent.name, file);
    agents.push(agent);
  }
  return agents;
};

export const toAgentToml = ({
  name,
  description,
  instructions,
}: AgentDefinition): string => {
  return [
    GENERATED_MARKER,
    `name = ${tomlString(name)}`,
    `description = ${tomlString(description)}`,
    `developer_instructions = ${tomlMultilineString(instructions)}`,
    "",
  ].join("\n");
};

/** 出力先パスが symlink なら、その解決先がソースツリー配下・同一でないことを検証する。 */
const assertSymlinkTargetOutsideSource = (
  path: string,
  pluginRootDir: string,
): void => {
  if (lstatSync(path, { throwIfNoEntry: false })?.isSymbolicLink()) {
    assertOutsideSource(path, pluginRootDir);
  }
};

export type GenerateAgentsTomlResult = {
  /** 出力した（同内容の既存を含む）件数 */
  count: number;
  /** 削除した、ソースに存在しない古い生成物の name */
  removed: string[];
  /** ソース md が 0 件のため古い生成物の削除をスキップした */
  staleCleanupSkipped: boolean;
};

/**
 * agentsSourceDir の *.md を <outputDir>/agents/<name>.toml へ変換する。
 * 内容が異なる既存ファイルは force 無しでは Error（何も書かない）。
 * ソースに存在しない名前の「GENERATED_MARKER 付き」.toml のみ削除し、その name を返す。
 */
export const generateAgentsToml = (
  outputDir: string,
  agentsSourceDir: string = SOURCE_AGENTS_DIR,
  pluginRootDir: string = SOURCE_PLUGIN_ROOT,
  options: { force?: boolean } = {},
): GenerateAgentsTomlResult => {
  assertOutsideSource(outputDir, pluginRootDir);
  const agentsOutputDir = join(resolve(outputDir), "agents");
  // agents/ 自体がソース側への symlink だと、配下への書き込み・削除がソースを破壊する
  assertOutsideSource(agentsOutputDir, pluginRootDir);

  const sources = readdirSync(agentsSourceDir)
    .filter((name) => name.endsWith(".md"))
    .map((file) => ({
      file,
      content: readFileSync(join(agentsSourceDir, file), "utf-8"),
    }));
  // 全件の変換・検証が済んでから書き出しに入る
  const agents = parseAgents(sources);
  const outputs = agents.map((agent) => ({
    name: agent.name,
    path: join(agentsOutputDir, `${agent.name}.toml`),
    toml: toAgentToml(agent),
  }));

  // 書き込み前に全件の衝突・種別・symlink を検査する（検査由来の失敗で一部だけ書かれるのを防ぐ。
  // 書き込み中の I/O 失敗（ディスクフル等）では、一部のファイルだけ置換済みの途中状態が残りうる）
  const conflicts: string[] = [];
  for (const { path, toml } of outputs) {
    const stat = lstatSync(path, { throwIfNoEntry: false });
    if (stat === undefined) {
      continue;
    }
    assertReplaceableOutput(path);
    assertSymlinkTargetOutsideSource(path, pluginRootDir);
    const isSameContent = stat.isFile() && readFileSync(path, "utf-8") === toml;
    if (!isSameContent && !options.force) {
      conflicts.push(path);
    }
  }
  if (conflicts.length > 0) {
    throw new Error(
      `既存ファイルが生成物と異なるため上書きしません（上書きするには --force を指定）: ${conflicts.join(", ")}`,
    );
  }

  mkdirSync(agentsOutputDir, { recursive: true });
  for (const { path, toml } of outputs) {
    // 一時ファイル経由の rename で、symlink / ハードリンクのリンク先ではなくエントリ自体を置換する
    writeFileReplacing(path, toml);
  }
  // ソース md が 0 件なら誤指定の可能性が高いため、生成物の削除はしない
  const staleCleanupSkipped = sources.length === 0;
  return {
    count: outputs.length,
    removed: staleCleanupSkipped
      ? []
      : removeStaleGenerated(
          agentsOutputDir,
          new Set(outputs.map(({ name }) => name)),
        ),
    staleCleanupSkipped,
  };
};

/** ソースに無い名前の、マーカー付き（本生成器の出力）通常ファイルのみ削除し、削除した name を返す。 */
const removeStaleGenerated = (
  agentsOutputDir: string,
  currentNames: Set<string>,
): string[] => {
  const removed: string[] = [];
  for (const file of readdirSync(agentsOutputDir)) {
    if (!file.endsWith(".toml")) {
      continue;
    }
    const name = file.slice(0, -".toml".length);
    const path = join(agentsOutputDir, file);
    if (currentNames.has(name) || !lstatSync(path).isFile()) {
      continue;
    }
    if (readFileSync(path, "utf-8").startsWith(GENERATED_MARKER + "\n")) {
      unlinkSync(path);
      removed.push(name);
    }
  }
  return removed.sort();
};

const USAGE = [
  "実行方法: node --experimental-strip-types generate-agents-toml.ts <出力先ディレクトリ> [--force]",
  "  --force: 内容が異なる既存の agents/<name>.toml を上書きする（指定が無ければ既存と差異がある場合は失敗）",
];

const main = () => {
  try {
    const { outputDir, flags } = parseOutputDirArgs(process.argv.slice(2), [
      "--force",
    ]);
    const { count, removed, staleCleanupSkipped } = generateAgentsToml(
      outputDir,
      SOURCE_AGENTS_DIR,
      SOURCE_PLUGIN_ROOT,
      { force: flags.has("--force") },
    );
    console.log(
      `Codex 向け agents TOML を ${count} 件出力しました: ${join(resolve(outputDir), "agents")}`,
    );
    if (staleCleanupSkipped) {
      console.log(
        "ソースの .md が 0 件のため、古い生成物の削除をスキップしました（ソースディレクトリ指定を確認してください）",
      );
    }
    if (removed.length > 0) {
      console.log(
        `ソースに無い古い生成物を ${removed.length} 件削除しました: ${removed.join(", ")}`,
      );
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    USAGE.forEach((line) => console.error(line));
    process.exit(1);
  }
};

if (isDirectRun(import.meta.url)) {
  main();
}
