/**
 * plugins/matagi/agents/*.md を、OpenCode のサブエージェント定義 <出力先>/agents/<name>.md へ変換するスクリプト。
 *
 * OpenCode の agents は Markdown + frontmatter で、ファイル名がエージェント名になる。
 * マッピング: frontmatter の description → description（`mode: subagent` を付与）、本文はそのまま。
 * name はファイル名側で表すため frontmatter には出力しない。frontmatter の解析・検証
 * （name / description 必須、name 形式、重複）は codex の generate-agents-toml.ts の parseAgents を再利用する。
 *
 * 安全性・上書き方針は codex の generate-agents-toml.ts と同じ:
 * - 出力先（および <出力先>/agents の symlink 解決後）がソースツリー配下・同一なら中止する。
 * - 内容が異なる既存の agents/<name>.md は --force 無しでは何も書かずに失敗する（同内容は冪等）。
 *   通常ファイルでも symlink でもない既存は --force でも拒否する。書き込みは一時ファイル経由の rename 置換。
 * - frontmatter 内の先頭コメント GENERATED_MARKER を持つ古い生成物のみ削除する（ユーザー自作は削除しない）。
 *   ソースの .md が 0 件のときは誤指定防止のため削除をスキップする。
 *
 * 実行方法: node --experimental-strip-types generate-agents-md.ts <出力先ディレクトリ（例: <repo>/.opencode）> [--force]
 */

import {
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  unlinkSync,
} from "node:fs";
import { join, resolve } from "node:path";
import {
  type AgentDefinition,
  parseAgents,
} from "../codex/generate-agents-toml.ts";
import {
  assertOutsideSource,
  assertReplaceableOutput,
  isDirectRun,
  parseOutputDirArgs,
  writeFileReplacing,
} from "../shared.ts";

const SOURCE_PLUGIN_ROOT = join(import.meta.dirname, "../../");
const SOURCE_AGENTS_DIR = join(SOURCE_PLUGIN_ROOT, "agents");

/** 本生成器の出力であることを示す、frontmatter 先頭の YAML コメント（古い出力の識別・削除に使う）。 */
export const GENERATED_MARKER =
  "# generated by matagi adapters/opencode/generate-agents-md.ts (do not edit; regenerate instead)";

export const toAgentMarkdown = ({
  description,
  instructions,
}: AgentDefinition): string => {
  return [
    "---",
    GENERATED_MARKER,
    // JSON の文字列表記は YAML のダブルクォート文字列としても妥当（コロン等を含む説明文を安全に出力できる）
    `description: ${JSON.stringify(description)}`,
    "mode: subagent",
    "---",
    "",
    instructions,
  ].join("\n");
};

const isGenerated = (content: string): boolean => {
  return content.startsWith(`---\n${GENERATED_MARKER}\n`);
};

export type GenerateAgentsMdResult = {
  count: number;
  removed: string[];
  staleCleanupSkipped: boolean;
};

export const generateAgentsMd = (
  outputDir: string,
  agentsSourceDir: string = SOURCE_AGENTS_DIR,
  pluginRootDir: string = SOURCE_PLUGIN_ROOT,
  options: { force?: boolean } = {},
): GenerateAgentsMdResult => {
  assertOutsideSource(outputDir, pluginRootDir);
  const agentsOutputDir = join(resolve(outputDir), "agents");
  // agents/ 自体がソース側への symlink だと、配下への書き込み・削除がソースを破壊する
  assertOutsideSource(agentsOutputDir, pluginRootDir);

  const sources = readdirSync(agentsSourceDir)
    .filter((name) => name.endsWith(".md"))
    .map((file) => ({
      file,
      content: readFileSync(join(agentsSourceDir, file), "utf-8"),
    }));
  // 全件の変換・検証が済んでから書き出しに入る
  const outputs = parseAgents(sources).map((agent) => ({
    name: agent.name,
    path: join(agentsOutputDir, `${agent.name}.md`),
    markdown: toAgentMarkdown(agent),
  }));

  const conflicts: string[] = [];
  for (const { path, markdown } of outputs) {
    const stat = lstatSync(path, { throwIfNoEntry: false });
    if (stat === undefined) {
      continue;
    }
    assertReplaceableOutput(path);
    if (stat.isSymbolicLink()) {
      assertOutsideSource(path, pluginRootDir);
    }
    const isSameContent =
      stat.isFile() && readFileSync(path, "utf-8") === markdown;
    if (!isSameContent && !options.force) {
      conflicts.push(path);
    }
  }
  if (conflicts.length > 0) {
    throw new Error(
      `既存ファイルが生成物と異なるため上書きしません（上書きするには --force を指定）: ${conflicts.join(", ")}`,
    );
  }

  mkdirSync(agentsOutputDir, { recursive: true });
  for (const { path, markdown } of outputs) {
    writeFileReplacing(path, markdown);
  }
  const staleCleanupSkipped = sources.length === 0;
  return {
    count: outputs.length,
    removed: staleCleanupSkipped
      ? []
      : removeStaleGenerated(
          agentsOutputDir,
          new Set(outputs.map(({ name }) => name)),
        ),
    staleCleanupSkipped,
  };
};

/** ソースに無い名前の、マーカー付き（本生成器の出力）通常ファイルのみ削除し、削除した name を返す。 */
const removeStaleGenerated = (
  agentsOutputDir: string,
  currentNames: Set<string>,
): string[] => {
  const removed: string[] = [];
  for (const file of readdirSync(agentsOutputDir)) {
    if (!file.endsWith(".md")) {
      continue;
    }
    const name = file.slice(0, -".md".length);
    const path = join(agentsOutputDir, file);
    if (currentNames.has(name) || !lstatSync(path).isFile()) {
      continue;
    }
    if (isGenerated(readFileSync(path, "utf-8"))) {
      unlinkSync(path);
      removed.push(name);
    }
  }
  return removed.sort();
};

const USAGE = [
  "実行方法: node --experimental-strip-types generate-agents-md.ts <出力先ディレクトリ> [--force]",
  "  --force: 内容が異なる既存の agents/<name>.md を上書きする（指定が無ければ既存と差異がある場合は失敗）",
];

const main = () => {
  try {
    const { outputDir, flags } = parseOutputDirArgs(process.argv.slice(2), [
      "--force",
    ]);
    const { count, removed, staleCleanupSkipped } = generateAgentsMd(
      outputDir,
      SOURCE_AGENTS_DIR,
      SOURCE_PLUGIN_ROOT,
      { force: flags.has("--force") },
    );
    console.log(
      `OpenCode 向け agents Markdown を ${count} 件出力しました: ${join(resolve(outputDir), "agents")}`,
    );
    if (staleCleanupSkipped) {
      console.log(
        "ソースの .md が 0 件のため、古い生成物の削除をスキップしました（ソースディレクトリ指定を確認してください）",
      );
    }
    if (removed.length > 0) {
      console.log(
        `ソースに無い古い生成物を ${removed.length} 件削除しました: ${removed.join(", ")}`,
      );
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    USAGE.forEach((line) => console.error(line));
    process.exit(1);
  }
};

if (isDirectRun(import.meta.url)) {
  main();
}
